spring:
  application:
    name: pms_assignment
  datasource:
    username: sa
    password: Abc123456@
    url: jdbc:sqlserver://localhost:1433;databaseName=pms_assignment;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      show-sql: auto
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  batch:
    initialize-schema: always     # Create tables for batch if these tables aren't existed (BATCH_JOB_INSTANCE, BATCH_JOB_EXECUTION,...)
    job:
      enabled: false              # Don't auto-run when app start ~ controlled by controller or scheduler

server:
  port: 8080

job:
  seeding-job:
    step3:
      in: file:D:/Programming/Java/pms_assignment/data/posts.csv 
